const pageInfo={railway:['Railway','1 of 3 lines connected'],lighting:['Lighting','2 circuits'],switches:['Switches','2 points']};
const navItems=[...document.querySelectorAll('.nav-item')];const pages=[...document.querySelectorAll('.page')];const sidebar=document.querySelector('.sidebar');
function showPage(id){navItems.forEach(item=>item.classList.toggle('active',item.dataset.page===id));pages.forEach(page=>page.classList.toggle('active',page.id===id));document.querySelector('#page-title').textContent=pageInfo[id][0];document.querySelector('#page-subtitle').textContent=pageInfo[id][1];sidebar.classList.remove('open');document.querySelector('#mobile-menu').setAttribute('aria-expanded','false');}
navItems.forEach(item=>item.addEventListener('click',()=>showPage(item.dataset.page)));document.querySelector('#mobile-menu').addEventListener('click',event=>{sidebar.classList.toggle('open');event.currentTarget.setAttribute('aria-expanded',sidebar.classList.contains('open'))});
const speed=document.querySelector('#speed');const speedOutput=document.querySelector('#speed-output');const statSpeed=document.querySelector('#stat-speed');const trainState=document.querySelector('#train-state');
function updateRange(input){input.style.setProperty('--value',`${input.value}%`)}
function setTrainSpeed(value){speed.value=value;updateRange(speed);speedOutput.textContent=`${value}%`;statSpeed.textContent=`${value}%`;const running=Number(value)>0;trainState.classList.toggle('running',running);trainState.innerHTML=running?'<span></span>Running':'Stopped'}
speed.addEventListener('input',()=>setTrainSpeed(speed.value));document.querySelector('#direction').addEventListener('click',event=>{if(!event.target.matches('button'))return;event.currentTarget.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button===event.target));document.querySelector('#stat-direction').textContent=event.target.dataset.direction;toast(`Direction changed to ${event.target.dataset.direction.toLowerCase()}`)});document.querySelector('#stop').addEventListener('click',()=>{setTrainSpeed(0);toast('Outer Loop stopped')});
document.querySelectorAll('.lighting-card').forEach(card=>{const toggle=card.querySelector('.toggle');const range=card.querySelector('.range');const output=card.querySelector('.brightness-output');updateRange(range);toggle.addEventListener('click',()=>{const on=!toggle.classList.contains('on');toggle.classList.toggle('on',on);toggle.setAttribute('aria-checked',on);card.classList.toggle('disabled',!on);range.disabled=!on;output.textContent=on?`${range.value}%`:'Off';toast(`${toggle.getAttribute('aria-label')} turned ${on?'on':'off'}`)});range.addEventListener('input',()=>{updateRange(range);output.textContent=`${range.value}%`})});
document.querySelectorAll('.point-control').forEach(control=>control.addEventListener('click',event=>{if(!event.target.matches('button'))return;const card=control.closest('.point-card');const route=event.target.dataset.route;control.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button===event.target));card.querySelector('.point-diagram').className=`point-diagram ${route.toLowerCase()}`;card.querySelector('.route-state').textContent=route;toast(`${card.querySelector('h3').textContent} set to ${route.toLowerCase()}`)}));
let toastTimer;function toast(message){const element=document.querySelector('#toast');element.textContent=message;element.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>element.classList.remove('show'),2200)}document.querySelectorAll('[data-demo-action]').forEach(button=>button.addEventListener('click',()=>toast('Demo limit reached — no hardware connected')));
document.querySelector('#reset-button').addEventListener('click',()=>{setTrainSpeed(62);document.querySelector('#stat-direction').textContent='Forward';document.querySelectorAll('.lighting-card').forEach((card,index)=>{const on=index===0;const range=card.querySelector('.range');const toggle=card.querySelector('.toggle');range.value=on?70:40;range.disabled=!on;updateRange(range);toggle.classList.toggle('on',on);toggle.setAttribute('aria-checked',on);card.classList.toggle('disabled',!on);card.querySelector('.brightness-output').textContent=on?'70%':'Off'});document.querySelectorAll('.segmented').forEach((group,index)=>group.querySelectorAll('button').forEach((button,buttonIndex)=>button.classList.toggle('active',buttonIndex===(index===2?1:0))));document.querySelectorAll('.point-card').forEach((card,index)=>{const route=index===0?'Straight':'Diverge';card.querySelector('.point-diagram').className=`point-diagram ${route.toLowerCase()}`;card.querySelector('.route-state').textContent=route});showPage('railway');toast('Demo restored to its initial state')});updateRange(speed);
